name = "IP DB Daily"
description = "Parse IP DB Daily"
cron_schedule = "0 0 9 * * * *"
stdout = "/home/zdeploy/huynx7/.rflow/jobs/ParseIPDBDaily.log"
stderr = "/home/zdeploy/huynx7/.rflow/jobs/ParseIPDBDaily.err"
[environments]
POLARS_MAX_THREADS = "12"

[[tasks]]
name = "Parse IP AUTHEN PC"
command = "dutils parse-ip -i /data/zminer/huynx7/IP-AUTHEN-PC-DISTINCT/$(date -d @$(expr $RFLOWTS - 86400) +%y-%m-%d)/part-00000 -o /data/rsync/huynx7/jobs/IP-AUTHEN-PC/$(date -d @$(expr $RFLOWTS - 86400) +%y-%m-%d)/parse-ip.pq -g /home/zdeploy/huynx7/workspace/tools/GeoLite2-City.mmdb"

[[tasks]]
name = "Parse IP AUTHEN COM"
command = "dutils parse-ip -i /data/zminer/huynx7/IP-AUTHEN-COM-DISTINCT/$(date -d @$(expr $RFLOWTS - 86400) +%y-%m-%d)/part-00000 -o /data/rsync/huynx7/jobs/IP-AUTHEN-COM/$(date -d @$(expr $RFLOWTS - 86400) +%y-%m-%d)/parse-ip.pq -g /home/zdeploy/huynx7/workspace/tools/GeoLite2-City.mmdb"
dependencies = ["Parse IP AUTHEN PC"]

[[tasks]]
name = "Run DBT"
command = "cd /home/zdeploy/huynx7/workspace/DAGSTER_DBT/dbt/ && /home/zdeploy/miniconda3/envs/dbt/bin/dbt run --vars \"{'running_date': '$(date -d @$(expr $RFLOWTS - 86400) +%y-%m-%d)'}\""
dependencies = ["Parse IP AUTHEN PC", "Parse IP AUTHEN COM"]

[[tasks]]
name = "Write IP Jumps"
command = "/home/zdeploy/miniconda3/envs/dbt/bin/python /home/zdeploy/huynx7/workspace/crontab/write_ip_jump.py $(date -d @$(expr $RFLOWTS - 86400) +%y-%m-%d)"
dependencies = ["Run DBT"]

