refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  file:
    kind: file
    path: "~/.rflow/log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} - {l:<5.10} - {t:<12.12} - {m}{n}"
root:
  level: debug 
  appenders:
    - stdout
    - file